{% set name = "flake8-bugbear" %}
{% set version = "23.7.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ebdc7d8ec1ca8bd49347694562381f099f4de2f8ec6bda7a7dca65555d9e0d4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8.1
    - pip
  run:
    - python >=3.8.1
    - flake8 >=6.0
    - attrs >=19.2.0

test:
  commands:
    - flake8 --version | grep flake8-bugbear

about:
  home: https://github.com/PyCQA/flake8-bugbear
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A plugin for Flake8 finding likely bugs and design problems in your program.

  description: |
    A plugin for Flake8 finding likely bugs and design problems in your
    program. Contains warnings that don't belong in pyflakes and pycodestyle.
  dev_url: https://github.com/PyCQA/flake8-bugbear

extra:
  recipe-maintainers:
    - dopplershift
